---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by swx.
--- DateTime: 2022/10/20 11:16
---    使用set集合 保证一人一单 同时 一个优惠券下能保存多个用户
--- 参数
local voucherId = ARGV[1]
local userId=ARGV[2]
local orderId=ARGV[3]

local stockKey ='seckill:stock:'..voucherId
local orderKey ='seckill:order:'..voucherId

if(tonumber(redis.call('get',stockKey)) <=0) then
    --库存不足 返回1
    return 1
end
---判断用户是否下单 Sismember
if(redis.call('sismember',orderKey,userId)==1) then
    ---存在 重复下单
    return 2
end
---扣库存
redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)
--- 发送消息到队列
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
return 0